FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./workspaces/backend/package*.json ./workspaces/backend/
COPY ./workspaces/shared/package*.json ./workspaces/shared/

RUN npm ci -w workspaces/backend

COPY ./workspaces/backend/ ./workspaces/backend/
COPY ./workspaces/shared/ ./workspaces/shared/

RUN npm run build -w workspaces/backend

EXPOSE 4000

CMD [ "node", "workspaces/backend/dist/app.js"]